import crypto from"node:crypto";import{getFirestore}from"firebase-admin/firestore";import{getStorage}from"firebase-admin/storage";import{FieldValue as CloudFieldValue}from"@google-cloud/firestore";import OpenAI from"openai";import pdf from"pdf-parse";
const db=getFirestore();export const EMBEDDING_MODEL=process.env.EMBEDDING_MODEL||"text-embedding-3-small";export const EMBEDDING_DIMENSIONS=1024;
export type RagFilter={grade?:number;subject?:string;skillId?:string};
function clean(s:string){return s.replace(/\u0000/g,"").replace(/[ \t]+/g," ").replace(/\n{3,}/g,"\n\n").trim()}
export function chunkText(text:string,maxChars=4200,overlap=500){const t=clean(text),out:string[]=[];let i=0;while(i<t.length){let end=Math.min(t.length,i+maxChars);if(end<t.length){const p=Math.max(t.lastIndexOf("\n\n",end),t.lastIndexOf(". ",end));if(p>i+maxChars*.6)end=p+1}const c=t.slice(i,end).trim();if(c)out.push(c);if(end>=t.length)break;i=Math.max(i+1,end-overlap)}return out}
export async function embed(openai:OpenAI,input:string[]){const r=await openai.embeddings.create({model:EMBEDDING_MODEL,input,dimensions:EMBEDDING_DIMENSIONS});return r.data.map(x=>x.embedding)}
export async function ingestPdfObject(openai:OpenAI,bucketName:string,objectName:string,meta:any={}){if(!objectName.toLowerCase().endsWith(".pdf"))throw new Error("Only PDF corpus objects are supported");const [buf]=await getStorage().bucket(bucketName).file(objectName).download();const sha256=crypto.createHash("sha256").update(buf).digest("hex");const docId=sha256.slice(0,32),docRef=db.doc(`ragDocuments/${docId}`);const existing=await docRef.get();if(existing.data()?.status==="indexed")return{docId,status:"already-indexed"};await docRef.set({objectName,bucketName,sha256,status:"parsing",publisher:meta.publisher||"Kenya Institute of Curriculum Development",sourceTitle:meta.sourceTitle||objectName,framework:meta.framework||"CBC/CBE",frameworkVersion:meta.frameworkVersion||null,grade:meta.grade?Number(meta.grade):null,subject:meta.subject||null,rights:meta.rights||"restricted-rag",createdAt:CloudFieldValue.serverTimestamp()},{merge:true});const parsed=await pdf(buf),chunks=chunkText(parsed.text);await docRef.set({status:"embedding",pageCount:parsed.numpages||null,chunkCount:chunks.length},{merge:true});for(let base=0;base<chunks.length;base+=32){const part=chunks.slice(base,base+32),vectors=await embed(openai,part),batch=db.batch();part.forEach((content,j)=>{const chunkIndex=base+j,id=`${docId}_${String(chunkIndex).padStart(5,"0")}`;batch.set(db.doc(`ragChunks/${id}`),{documentId:docId,chunkIndex,content,contentHash:crypto.createHash("sha256").update(content).digest("hex"),embedding:CloudFieldValue.vector(vectors[j]),publisher:meta.publisher||"Kenya Institute of Curriculum Development",sourceTitle:meta.sourceTitle||objectName,framework:meta.framework||"CBC/CBE",frameworkVersion:meta.frameworkVersion||null,grade:meta.grade?Number(meta.grade):null,subject:meta.subject||null,skillIds:String(meta.skillIds||"").split(",").map((x:string)=>x.trim()).filter(Boolean),objectName,rights:meta.rights||"restricted-rag",createdAt:CloudFieldValue.serverTimestamp()})});await batch.commit()}await docRef.set({status:"indexed",indexedAt:CloudFieldValue.serverTimestamp()},{merge:true});return{docId,status:"indexed",chunks:chunks.length}}
export async function retrieve(openai:OpenAI,question:string,filter:RagFilter={},k=7){const [qv]=await embed(openai,[question]);let q:any=db.collection("ragChunks");if(filter.grade)q=q.where("grade","==",filter.grade);if(filter.subject)q=q.where("subject","==",filter.subject);const snap=await q.findNearest({vectorField:"embedding",queryVector:qv,limit:Math.min(12,Math.max(1,k)),distanceMeasure:"COSINE",distanceResultField:"distance"}).get();return snap.docs.map((d:any)=>{const x=d.data();return{id:d.id,documentId:x.documentId,content:x.content,sourceTitle:x.sourceTitle,publisher:x.publisher,frameworkVersion:x.frameworkVersion,grade:x.grade,subject:x.subject,chunkIndex:x.chunkIndex,distance:x.distance}}).filter((x:any)=>!filter.skillId||!x.skillIds||x.skillIds.includes(filter.skillId))}
export function ragContext(rows:any[]){return rows.map((x,i)=>`[SOURCE ${i+1}: ${x.sourceTitle}; chunk ${x.chunkIndex}]\n${x.content}`).join("\n\n")}
