import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart';
import 'services/funzi_api.dart';import 'services/funzi_data.dart';import 'models/learner_twin.dart';import 'features/learning_pages.dart';import 'features/parity_pages.dart';import 'science/deterministic_science_page.dart';import 'science/visual_labs_page.dart';
Future<void> main() async {WidgetsFlutterBinding.ensureInitialized();await Firebase.initializeApp(options:DefaultFirebaseOptions.currentPlatform);runApp(const FunziApp());}
class FunziApp extends StatelessWidget{const FunziApp({super.key});@override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Funzi',theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xff2c8c79)),home:const AuthGate());}
class AuthGate extends StatelessWidget{const AuthGate({super.key});@override Widget build(BuildContext context)=>StreamBuilder<User?>(stream:FirebaseAuth.instance.authStateChanges(),builder:(c,s)=>s.data==null?const LoginPage():const HomePage());}
class LoginPage extends StatefulWidget{const LoginPage({super.key});@override State<LoginPage> createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{final email=TextEditingController(),password=TextEditingController();String? error;Future<void> login()async{try{await FirebaseAuth.instance.signInWithEmailAndPassword(email:email.text.trim(),password:password.text);}catch(e){setState(()=>error=e.toString());}}@override Widget build(BuildContext context)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('FUNZI',style:Theme.of(context).textTheme.displaySmall),const Text('Adaptive learning, inquiry and mastery.'),const SizedBox(height:24),TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password')),if(error!=null)Text(error!),const SizedBox(height:16),FilledButton(onPressed:login,child:const Text('Sign in'))])))));}
class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage>createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{LearnerTwin?twin;bool loading=true;String page='Overview';@override void initState(){super.initState();FunziData.twin().then((x)=>setState((){twin=x;loading=false;}));}Widget body(){if(loading)return const Center(child:CircularProgressIndicator());final t=twin??const LearnerTwin(grade:8,streak:0,xp:0,weeklyMinutes:0,language:'English',skills:[]);return switch(page){'Tutor'=>const TutorPage(),'Experiences'=>ExperiencesPage(t),'Practice'=>PracticePage(t),'Science Lab'=>GeneratedSciencePage(t.skills.isEmpty?'general':t.skills.first.id),'Deterministic Lab'=>const DeterministicSciencePage(),'Inquiry Lab'=>const ScienceLabPage(),'Visual Labs'=>const VisualLabsPage(),'Mastery'=>MasteryPage(t),'Portfolio'=>const PortfolioParityPage(),'Plan'=>PlanPage(t),'Leaderboard'=>const LeaderboardPage(),'Teacher'=>TeacherPage(t),'Parent'=>ParentPage(t),_=>DashboardPage(t)};}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('Funzi · $page'),actions:[PopupMenuButton<String>(onSelected:(v)=>setState(()=>page=v),itemBuilder:(_)=>['Overview','Tutor','Experiences','Practice','Science Lab','Deterministic Lab','Inquiry Lab','Visual Labs','Mastery','Portfolio','Plan','Leaderboard','Teacher','Parent'].map((x)=>PopupMenuItem(value:x,child:Text(x))).toList()),IconButton(onPressed:()=>FirebaseAuth.instance.signOut(),icon:const Icon(Icons.logout))]),body:body(),bottomNavigationBar:NavigationBar(selectedIndex:['Overview','Tutor','Science Lab','Portfolio'].indexOf(page)<0?0:['Overview','Tutor','Science Lab','Portfolio'].indexOf(page),onDestinationSelected:(i)=>setState(()=>page=['Overview','Tutor','Science Lab','Portfolio'][i]),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.psychology_outlined),label:'Tutor'),NavigationDestination(icon:Icon(Icons.science_outlined),label:'Lab'),NavigationDestination(icon:Icon(Icons.folder_outlined),label:'Portfolio')])));}
class DashboardPage extends StatelessWidget{final LearnerTwin twin;const DashboardPage(this.twin,{super.key});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[Text('Learning command center',style:Theme.of(context).textTheme.headlineMedium),Wrap(spacing:8,runSpacing:8,children:[Chip(label:Text('Grade ${twin.grade}')),Chip(label:Text('${twin.streak} day streak')),Chip(label:Text('${twin.xp} XP')),Chip(label:Text('${twin.weeklyMinutes} min/week'))]),...twin.skills.map((s)=>Card(child:ListTile(title:Text(s.name),subtitle:LinearProgressIndicator(value:s.mastery),trailing:Text('${(s.mastery*100).round()}%'))))]);}
class TutorPage extends StatefulWidget{const TutorPage({super.key});@override State<TutorPage> createState()=>_TutorPageState();}
class _TutorPageState extends State<TutorPage>{final input=TextEditingController();String answer='';bool busy=false;Future<void> ask()async{setState(()=>busy=true);try{final r=await FunziApi.tutor(input.text);setState(()=>answer=r['text']??'');}finally{setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(20),child:Column(children:[Expanded(child:SingleChildScrollView(child:SelectableText(answer.isEmpty?'Ask Funzi a question.':answer))),TextField(controller:input,minLines:1,maxLines:4,decoration:InputDecoration(suffixIcon:IconButton(onPressed:busy?null:ask,icon:const Icon(Icons.send)),hintText:'Explain a concept…'))]));}
class ScienceLabPage extends StatefulWidget{const ScienceLabPage({super.key});@override State<ScienceLabPage> createState()=>_ScienceLabPageState();}
class _ScienceLabPageState extends State<ScienceLabPage>{final hyp=TextEditingController(),iv=TextEditingController(),dv=TextEditingController(),method=TextEditingController(),data=TextEditingController(text:'x,y\n1,2\n2,4\n3,6');String status='';String? id;Future<void> save({bool submit=false})async{final r=await FunziApi.saveNotebook({'notebookId':id,'labId':'inquiry-general','title':'Inquiry notebook','question':'Investigate a measurable relationship','hypothesis':hyp.text,'independentVariable':iv.text,'dependentVariable':dv.text,'controlledVariables':[],'method':method.text.split('\n').where((x)=>x.trim().isNotEmpty).toList(),'dataCsv':data.text,'conclusion':'','limitations':[],'reflection':''});id=r['id'];if(submit)await FunziApi.submitNotebook(id!);setState(()=>status=submit?'Submitted as trusted portfolio evidence.':'Draft saved.');}@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[Text('Science Lab 2.0',style:Theme.of(context).textTheme.headlineMedium),TextField(controller:hyp,decoration:const InputDecoration(labelText:'Hypothesis')),TextField(controller:iv,decoration:const InputDecoration(labelText:'Independent variable')),TextField(controller:dv,decoration:const InputDecoration(labelText:'Dependent variable')),TextField(controller:method,maxLines:5,decoration:const InputDecoration(labelText:'Method')),TextField(controller:data,maxLines:6,decoration:const InputDecoration(labelText:'CSV observations')),const SizedBox(height:12),Wrap(spacing:8,children:[FilledButton(onPressed:()=>save(),child:const Text('Save draft')),OutlinedButton(onPressed:()=>save(submit:true),child:const Text('Submit evidence'))]),if(status.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Text(status))]);}
class PortfolioPage extends StatelessWidget{const PortfolioPage({super.key});@override Widget build(BuildContext context){final uid=FirebaseAuth.instance.currentUser!.uid;return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseFirestore.instance.collection('portfolios').doc(uid).collection('evidence').orderBy('createdAt',descending:true).snapshots(),builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(20),children:[Text('Portfolio',style:Theme.of(context).textTheme.headlineMedium),...s.data!.docs.map((d)=>Card(child:ListTile(title:Text(d.data()['title']??'Evidence'),subtitle:Text(d.data()['teacherVerified']==true?'Teacher verified':'Awaiting review'))))]);});}}
