export type LabDomain="physics"|"chemistry"|"biology"|"earth"|"astronomy"|"engineering"|"computational"|"microscopy";
export type LabSpec={id:string;title:string;domain:LabDomain;mode:"simulation"|"real_data"|"hybrid";solverId?:string;objective:string;misconceptions:string[];instruments:string[];skills:string[];discoverableLaw?:string;extensions:string[]};
export const LABS:LabSpec[]=[
{id:"ohms-discovery",title:"Discover Ohm's law",domain:"physics",mode:"hybrid",solverId:"circuit",objective:"Infer the voltage-current-resistance relationship from trials.",misconceptions:["current is used up","voltage equals current"],instruments:["multimeter"],skills:["variables","graphing","circuits"],discoverableLaw:"V=IR",extensions:["fault finding","unknown resistance"]},
{id:"lens-unknown",title:"Find an unknown focal length",domain:"physics",mode:"hybrid",solverId:"thin_lens",objective:"Determine focal length from object and image distances.",misconceptions:["image always same size"],instruments:["ruler"],skills:["optics","measurement"],extensions:["ray diagram"]},
{id:"titration-unknown",title:"Unknown concentration by titration",domain:"chemistry",mode:"hybrid",solverId:"titration",objective:"Estimate unknown concentration from equivalence.",misconceptions:["equivalence always means neutral"],instruments:["burette","pH sensor"],skills:["stoichiometry","graphing"],extensions:["weak acids"]},
{id:"enzyme-investigation",title:"Enzyme rate investigation",domain:"biology",mode:"simulation",solverId:"michaelis_menten",objective:"Investigate substrate concentration and rate.",misconceptions:["rate rises forever"],instruments:["stopwatch"],skills:["rates","enzymes"],extensions:["temperature model"]},
{id:"population-field-study",title:"Population dynamics",domain:"biology",mode:"simulation",solverId:"logistic_population",objective:"Explore carrying capacity and growth.",misconceptions:["populations grow exponentially forever"],instruments:["counter"],skills:["ecology","graphs"],extensions:["food web"]},
{id:"seismic-location",title:"Seismic arrival investigation",domain:"earth",mode:"simulation",solverId:"seismic_travel",objective:"Use P and S arrivals to reason about distance.",misconceptions:["P and S waves have same speed"],instruments:["seismograph"],skills:["waves","earthquakes"],extensions:["triangulation"]},
{id:"radiometric-time",title:"Geological time from decay",domain:"earth",mode:"simulation",solverId:"radioactive_decay",objective:"Connect half-life to geological age.",misconceptions:["half-life changes with sample size"],instruments:["counter"],skills:["decay","geologic time"],extensions:["stratigraphy"]},
{id:"orbit-lab",title:"Orbital systems",domain:"astronomy",mode:"simulation",objective:"Investigate orbital relationships.",misconceptions:["planets need continuous thrust"],instruments:["virtual telescope"],skills:["gravity","models"],extensions:["phases","spectra"]},
{id:"microscope-cells",title:"Microscope measurement",domain:"microscopy",mode:"hybrid",objective:"Measure and classify microscopic structures.",misconceptions:["magnification increases resolution indefinitely"],instruments:["microscope","eyepiece scale"],skills:["cells","measurement"],extensions:["annotation"]},
{id:"engineering-design",title:"Engineering constraint challenge",domain:"engineering",mode:"simulation",objective:"Optimize a design against constraints.",misconceptions:["strongest design is always best"],instruments:["virtual load sensor"],skills:["optimization","forces"],extensions:["cost","materials"]},
{id:"computational-model",title:"Computational science sandbox",domain:"computational",mode:"simulation",objective:"Change safe model parameters and compare predictions.",misconceptions:["models are exact reality"],instruments:["data logger"],skills:["modeling","coding","graphs"],extensions:["parameter sweep"]}]