export type Trial={id:string;inputs:Record<string,number>;measurements:Record<string,number>;timestamp:number};export type LabNotebook={id:string;learnerId:string;experimentId:string;title:string;question:string;hypothesis:string;independentVariable:string;dependentVariable:string;controlledVariables:string[];method:string[];trials:Trial[];conclusion:string;limitations:string[];reflection:string;status:"draft"|"submitted"|"reviewed";};
export type Instrument={id:string;name:string;unit:string;resolution:number;min:number;max:number;noiseStd?:number};
export type PracticalRubric={experimentalDesign:number;variableControl:number;measurement:number;graphing:number;interpretation:number;conclusion:number;safety:number};
export const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);
export const sampleSD=(x:number[])=>x.length<2?0:Math.sqrt(x.reduce((s,v)=>s+(v-mean(x))**2,0)/(x.length-1));
export const standardError=(x:number[])=>x.length?sampleSD(x)/Math.sqrt(x.length):0;
export function measure(trueValue:number,i:Instrument,noise=0){const raw=Math.max(i.min,Math.min(i.max,trueValue+noise));return Math.round(raw/i.resolution)*i.resolution}
export function summarize(x:number[]){return{n:x.length,mean:mean(x),sd:sampleSD(x),standardError:standardError(x),min:x.length?Math.min(...x):0,max:x.length?Math.max(...x):0}}
export function linearRegression(points:{x:number;y:number}[]){const n=points.length;if(n<2)throw Error("At least two points required");const sx=points.reduce((a,p)=>a+p.x,0),sy=points.reduce((a,p)=>a+p.y,0),sxx=points.reduce((a,p)=>a+p.x*p.x,0),sxy=points.reduce((a,p)=>a+p.x*p.y,0),den=n*sxx-sx*sx;if(Math.abs(den)<1e-12)throw Error("X values need variation");const slope=(n*sxy-sx*sy)/den,intercept=(sy-slope*sx)/n,my=sy/n,ssTot=points.reduce((a,p)=>a+(p.y-my)**2,0),ssRes=points.reduce((a,p)=>a+(p.y-(slope*p.x+intercept))**2,0);return{slope,intercept,r2:ssTot?1-ssRes/ssTot:1,residuals:points.map(p=>({x:p.x,y:p.y-(slope*p.x+intercept)}))}}
export function percentError(measured:number,accepted:number){return accepted===0?null:Math.abs((measured-accepted)/accepted)*100}
export function rssUncertainty(values:{value:number;uncertainty:number;power:number}[]){const relative=Math.sqrt(values.reduce((s,v)=>s+(v.power*v.uncertainty/v.value)**2,0));return relative}
export function gradePractical(r:PracticalRubric){const vals=Object.values(r);return Math.round(vals.reduce((a,b)=>a+b,0)/(vals.length*4)*100)}
export type Challenge={id:string;kind:"unknown"|"fault"|"discover";prompt:string;hiddenKey?:string;acceptedValue?:number;tolerance?:number;faults?:string[]};
export function checkChallenge(c:Challenge,answer:number|string){if(c.kind==="unknown"&&typeof answer==="number"&&c.acceptedValue!==undefined){const tol=c.tolerance??.05;return Math.abs(answer-c.acceptedValue)<=Math.max(Math.abs(c.acceptedValue)*tol,tol)}if(c.kind==="fault")return c.faults?.some(f=>String(answer).toLowerCase().includes(f.toLowerCase()))??false;return false}