export type Point={x:number;y:number};export type SolverResult={metrics:Record<string,number|string>;series?:{name:string;xLabel:string;yLabel:string;points:Point[]}[];geometry?:any;notes?:string[]};const finite=(...n:number[])=>n.every(Number.isFinite);const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
export function circuit(p:{voltage:number;resistors:number[];mode:"series"|"parallel"}):SolverResult{if(!finite(p.voltage,...p.resistors)||p.voltage<0||p.voltage>240||!p.resistors.length||p.resistors.some(r=>r<=0))throw Error("Invalid circuit values");const R=p.mode==="series"?p.resistors.reduce((a,b)=>a+b,0):1/p.resistors.reduce((a,r)=>a+1/r,0),I=p.voltage/R;return{metrics:{equivalentResistance:R,current:I,power:p.voltage*I},notes:["Ideal DC resistive circuit"]}}
export function mechanics(p:{u:number;a:number;t:number}):SolverResult{if(!finite(p.u,p.a,p.t)||p.t<0||p.t>120)throw Error("Invalid mechanics values");const pts=Array.from({length:41},(_,i)=>{const t=p.t*i/40;return{x:t,y:p.u*t+.5*p.a*t*t}});return{metrics:{finalVelocity:p.u+p.a*p.t,displacement:p.u*p.t+.5*p.a*p.t*p.t},series:[{name:"Displacement",xLabel:"Time (s)",yLabel:"Displacement (m)",points:pts}]}}
export function projectile(p:{speed:number;angleDeg:number;gravity?:number}):SolverResult{const g=p.gravity??9.81,a=p.angleDeg*Math.PI/180;if(!finite(p.speed,a,g)||p.speed<0||p.speed>200||g<=0)throw Error("Invalid projectile values");const T=2*p.speed*Math.sin(a)/g,R=p.speed*Math.cos(a)*T,H=(p.speed*Math.sin(a))**2/(2*g),pts=Array.from({length:51},(_,i)=>{const t=T*i/50;return{x:p.speed*Math.cos(a)*t,y:Math.max(0,p.speed*Math.sin(a)*t-.5*g*t*t)}});return{metrics:{flightTime:T,range:R,maxHeight:H},series:[{name:"Trajectory",xLabel:"Horizontal distance (m)",yLabel:"Height (m)",points:pts}]}}
export function thinLens(p:{focalLength:number;objectDistance:number;objectHeight?:number}):SolverResult{const{focalLength:f,objectDistance:u}=p;if(!finite(f,u)||f===0||u===0||Math.abs(u-f)<1e-8)throw Error("Invalid lens geometry");const v=1/(1/f-1/u),m=-v/u,h=(p.objectHeight??1)*m;return{metrics:{imageDistance:v,magnification:m,imageHeight:h},geometry:{lensX:0,objectX:-u,imageX:v,focalLength:f,objectHeight:p.objectHeight??1,imageHeight:h}}}
export function dilution(p:{c1:number;v1:number;v2:number}):SolverResult{if(!finite(p.c1,p.v1,p.v2)||p.c1<0||p.v1<0||p.v2<=0||p.v1>p.v2)throw Error("Invalid dilution values");return{metrics:{c2:p.c1*p.v1/p.v2}}}
export function firstOrderKinetics(p:{c0:number;k:number;duration:number}):SolverResult{if(!finite(p.c0,p.k,p.duration)||p.c0<0||p.k<0||p.duration<0)throw Error("Invalid kinetics values");const pts=Array.from({length:51},(_,i)=>{const x=p.duration*i/50;return{x,y:p.c0*Math.exp(-p.k*x)}});return{metrics:{finalConcentration:p.c0*Math.exp(-p.k*p.duration),halfLife:p.k?Math.log(2)/p.k:Infinity},series:[{name:"Concentration",xLabel:"Time",yLabel:"Concentration",points:pts}]}}
export function punnett(p:{parentA:"AA"|"Aa"|"aa";parentB:"AA"|"Aa"|"aa"}):SolverResult{const gam=(g:string)=>g==="AA"?["A","A"]:g==="aa"?["a","a"]:["A","a"],counts:Record<string,number>={AA:0,Aa:0,aa:0};for(const a of gam(p.parentA))for(const b of gam(p.parentB)){const g=a+b;counts[g==="AA"?"AA":g==="aa"?"aa":"Aa"]++}return{metrics:{AA:counts.AA/4,Aa:counts.Aa/4,aa:counts.aa/4,dominantPhenotype:(counts.AA+counts.Aa)/4,recessivePhenotype:counts.aa/4}}}
export function logisticPopulation(p:{n0:number;r:number;k:number;steps:number;dt?:number}):SolverResult{if(!finite(p.n0,p.r,p.k,p.steps)||p.n0<0||p.k<=0||p.steps<1||p.steps>500)throw Error("Invalid population values");let n=p.n0;const dt=p.dt??1,pts=[{x:0,y:n}];for(let i=1;i<=p.steps;i++){n=clamp(n+p.r*n*(1-n/p.k)*dt,0,p.k*2);pts.push({x:i*dt,y:n})}return{metrics:{finalPopulation:n,carryingCapacity:p.k},series:[{name:"Population",xLabel:"Time",yLabel:"Population",points:pts}]}}
export function radioactiveDecay(p:{initial:number;halfLife:number;duration:number}):SolverResult{if(!finite(p.initial,p.halfLife,p.duration)||p.initial<0||p.halfLife<=0||p.duration<0)throw Error("Invalid decay values");const pts=Array.from({length:51},(_,i)=>{const x=p.duration*i/50;return{x,y:p.initial*2**(-x/p.halfLife)}});return{metrics:{remaining:p.initial*2**(-p.duration/p.halfLife),fractionRemaining:2**(-p.duration/p.halfLife)},series:[{name:"Parent isotope",xLabel:"Time",yLabel:"Amount",points:pts}]}}
export type SolverId="circuit"|"mechanics"|"projectile"|"thin_lens"|"dilution"|"first_order_kinetics"|"punnett"|"logistic_population"|"radioactive_decay";
export function solve(id:SolverId,p:any):SolverResult{switch(id){case"circuit":return circuit(p);case"mechanics":return mechanics(p);case"projectile":return projectile(p);case"thin_lens":return thinLens(p);case"dilution":return dilution(p);case"first_order_kinetics":return firstOrderKinetics(p);case"punnett":return punnett(p);case"logistic_population":return logisticPopulation(p);case"radioactive_decay":return radioactiveDecay(p)}}