export type XY={x:number;y:number};export type VisualNode={id:string;kind:string;label:string;position:XY;data:Record<string,any>};export type VisualEdge={id:string;from:string;to:string;kind:string;data:Record<string,any>};export type VisualModel={id:string;type:"kirchhoff"|"food_web"|"pedigree"|"free_body"|"geologic_timeline";nodes:VisualNode[];edges:VisualEdge[]};
export const uid=(p="n")=>p+Math.random().toString(36).slice(2,8);
export function moveNode(m:VisualModel,id:string,p:XY):VisualModel{return{...m,nodes:m.nodes.map(n=>n.id===id?{...n,position:{x:Math.max(4,Math.min(96,p.x)),y:Math.max(5,Math.min(95,p.y))}}:n)}}
export function addNode(m:VisualModel,kind:string,label:string,data:Record<string,any>={}):VisualModel{return{...m,nodes:[...m.nodes,{id:uid(),kind,label,position:{x:20+(m.nodes.length*13)%65,y:20+(m.nodes.length*17)%60},data}]}}
export function removeNode(m:VisualModel,id:string):VisualModel{return{...m,nodes:m.nodes.filter(n=>n.id!==id),edges:m.edges.filter(e=>e.from!==id&&e.to!==id)}}
export function connect(m:VisualModel,from:string,to:string,kind:string,data:Record<string,any>={}):VisualModel{return from===to?m:{...m,edges:[...m.edges,{id:uid("e"),from,to,kind,data}]}}
export function toKirchhoff(m:VisualModel){const ground=m.nodes.find(n=>n.kind==="ground")?.id||m.nodes[0]?.id;return{nodes:m.nodes.map(n=>n.id),ground,resistors:m.edges.filter(e=>e.kind==="resistor").map(e=>({a:e.from,b:e.to,r:Number(e.data.r)||10})),currents:m.nodes.filter(n=>Number(n.data.current)).map(n=>({node:n.id,amps:Number(n.data.current)}))}}
export function toFoodWeb(m:VisualModel){return{populations:Object.fromEntries(m.nodes.map(n=>[n.id,Number(n.data.population)||10])),growth:Object.fromEntries(m.nodes.map(n=>[n.id,Number(n.data.growth)||0])),interactions:m.edges.map(e=>({from:e.from,to:e.to,rate:Number(e.data.rate)||.001})),steps:80,dt:.05}}
export function toFreeBody(m:VisualModel){return{mass:Number(m.nodes[0]?.data.mass)||1,forces:m.edges.map(e=>({x:Number(e.data.fx)||0,y:Number(e.data.fy)||0,label:e.data.label||e.kind}))}}
export function toTimeline(m:VisualModel){const ages=m.nodes.map(n=>Number(n.data.ageMa)||0);return{startMa:Math.max(1,...ages),endMa:Math.min(0,...ages),events:m.nodes.map(n=>({ageMa:Number(n.data.ageMa)||0,label:n.label}))}}